# Generated by Django 3.2.16 on 2022-12-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('toothbrush_type', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('customer_age', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('billing_postcode', models.CharField(max_length=20)),
                ('is_first', models.BooleanField()),
                ('dispatch_status', models.CharField(max_length=30)),
                ('dispatch_date', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=30)),
                ('delivery_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NullOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('toothbrush_type', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('customer_age', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('billing_postcode', models.CharField(max_length=20)),
                ('is_first', models.BooleanField()),
                ('dispatch_status', models.CharField(blank=True, max_length=30, null=True)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TodaysOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('toothbrush_type', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('customer_age', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('billing_postcode', models.CharField(max_length=20)),
                ('is_first', models.BooleanField()),
                ('dispatch_status', models.CharField(max_length=30)),
                ('dispatch_date', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=30)),
                ('delivery_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
