# Generated by Django 3.2.16 on 2022-12-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221223_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpostcode',
            name='full_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_postcode_full', to='core.fullorder'),
        ),
        migrations.AlterField(
            model_name='billingpostcode',
            name='null_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_postcode_null', to='core.nullorder'),
        ),
        migrations.AlterField(
            model_name='billingpostcode',
            name='todays_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_postcode_today', to='core.todaysorder'),
        ),
        migrations.AlterField(
            model_name='deliverypostcode',
            name='full_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_postcode_full', to='core.fullorder'),
        ),
        migrations.AlterField(
            model_name='deliverypostcode',
            name='null_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_postcode_null', to='core.nullorder'),
        ),
        migrations.AlterField(
            model_name='deliverypostcode',
            name='todays_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_postcode_today', to='core.todaysorder'),
        ),
    ]
