# Generated by Django 3.2.16 on 2022-12-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221223_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingpostcode',
            name='full_order',
        ),
        migrations.RemoveField(
            model_name='billingpostcode',
            name='null_order',
        ),
        migrations.RemoveField(
            model_name='billingpostcode',
            name='todays_order',
        ),
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='full_order',
        ),
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='null_order',
        ),
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='todays_order',
        ),
        migrations.AddField(
            model_name='fullorder',
            name='billing_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_billing_pc', to='core.billingpostcode'),
        ),
        migrations.AddField(
            model_name='fullorder',
            name='delivery_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_delivery_pc', to='core.deliverypostcode'),
        ),
        migrations.AddField(
            model_name='nullorder',
            name='billing_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='null_billing_pc', to='core.billingpostcode'),
        ),
        migrations.AddField(
            model_name='nullorder',
            name='delivery_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='null_delivery_pc', to='core.deliverypostcode'),
        ),
        migrations.AddField(
            model_name='todaysorder',
            name='billing_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_billing_pc', to='core.billingpostcode'),
        ),
        migrations.AddField(
            model_name='todaysorder',
            name='delivery_postcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_delivery_pc', to='core.deliverypostcode'),
        ),
    ]
