# Generated by Django 3.2.16 on 2022-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221225_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpostcode',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='billingpostcode',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='billingpostcode',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='billingpostcode',
            name='postcode_area',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='deliverypostcode',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deliverypostcode',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deliverypostcode',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deliverypostcode',
            name='postcode_area',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
