# Generated by Django 4.0.8 on 2023-01-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221228_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingpostcode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingpostcode',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='billingpostcode',
            name='longitude',
        ),
    ]
