# Generated by Django 4.0.8 on 2023-01-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_billingpostcode_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliverypostcode',
            name='longitude',
        ),
    ]
